# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

baseURL: "https://briandvorsky.com"
defaultContentLanguage: "en"

# pluralizeListTitles: "true" # hugo function useful for non-english languages

enableRobotsTXT: true
summaryLength: 25

buildDrafts: true
buildFuture: false

enableEmoji: true

# googleAnalytics: "G-XXXXXXXXX"

caches:
  images:
    dir: ":cacheDir/images"

pagination:
  pagerSize: 100

imaging:
  anchor: "Center"

taxonomies:
  tag: "tags"
  category: "categories"
  author: "authors"
  series: "series"

sitemap:
  changefreq: "daily"
  filename: "sitemap.xml"
  priority: 0.5

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"

related:
  threshold: 0
  toLower: false
  indices:
    - name: "tags"
      weight: 100
    - name: "categories"
      weight: 100
    - name: "series"
      weight: 50
    - name: "authors"
      weight: 20
    - name: "date"
      weight: 10
    - name: "fragmentrefs"
      applyFilter: false
      type: "fragments"
      weight: 10